import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import SessionWrapper from '@/app/auth/SessionWrapper';

const localFont1 = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const localFont2 = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SessionWrapper>
      <html lang="en">
        <body className={`${localFont1.variable} ${localFont2.variable} antialiased`}>
          {children}
        </body>
      </html>
    </SessionWrapper>
  );
}
